### ISSUE TITLE
Widget throws JS exception if Google JS is not loaded

### ISSUE THREAD

**Issue by spiderpug** [Scrivito/scrivito_google_maps_widget#3]
The readme states that one should include Google's JS:

> Include the Google Maps Places JavaScript library in your application.html.erb:

but this is not necessary if the website is using the maps widget for specific page types only, for example. The motivation to exclude Google's JS would be improved loading speed or reduction of data usage.

Could we update the JS to check for presence of `google` before initializing? See https://github.com/Scrivito/scrivito_google_maps_widget/blob/master/app/assets/javascripts/scrivito_google_maps_widget/application.js.coffee#L57 for example. Other source location are affected as well.

I suggest to just skip the initialization if Google JS is not loaded.

**Comment by gertimon** [comment]
If i understand this issue correct, i see three possible ways:
- Add a Content_for block for the specific type
- Something like `include_google_maps if @obj.it_is_a_type_with_a_google_maps`
- Something like `include_google_maps if (@obj.widgets.select {|w| w.is_a? GoogleMapsWidget}).present? `

**Comment by spiderpug** [comment]
It's clear how to including the google maps JS on demand.

The problem however is that the inclusion of `scrivito_google_maps_widget` (in `application.js`) throws JS exceptions if the google maps JS is not present.

**Comment by gertimon** [comment]
The only way i see here is to add the problematic code in a separate file, add this to assetpipeline, and include it in the application layout.
 
I will see if i can add a check `if the google api is loaded` to the gem. Sounds like the best way.

**Comment by spiderpug** [comment]
> I will see if i can add a check if the google api is loaded to the gem. Sounds like the best way.

Agreed ;-)

`google?.maps.event...` should be sufficient to dodge that problem in the example given above or am I missing something?

**Comment by gertimon** [comment]
Added in V 0.1.11
Problem exists with adding a new Widget to the page. The page has to be reloaded.
